apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-service
  namespace: proving-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-service
  template:
    metadata:
      labels:
        app: camunda-service
    spec:
      initContainers:
          - name: wait-for-zeebe
            image: busybox
            command: ['sh', '-c', 'until nc -z camunda-zeebe-gateway 26500; do echo waiting for Zeebe...; sleep 2; done']
      containers:
      - name: camunda-service
        image: camunda-service:latest
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8000
        env:
        - name: ZEEBE_ADDRESS
          value: "camunda-zeebe-gateway:26500" # host:port form, da  Zeebe gRPC erwartet nicht HTTP
        - name: PROOFING_SERVICE_API_URL
          value: "http://proofing-service:3000" #http connection
        - name: SENSOR_SERVICE_API_URL
          value: "http://sensor-data-service:8080" #http connection
        - name: LOG_LEVEL
          value: "INFO"
        - name: ACTIVITIES_OUTPUT_PATH
          value: "/app/activities.json" # Pfad innerhalb des Containers
        - name: REQUEST_TIMEOUT
          value: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: camunda-service
spec:
  selector:
    app: camunda-service
  ports:
    - port: 8000
      targetPort: 8000